

simul:
  probas: |
    {
    "loc_probas": {
        "0": 0.5,
        "1": 0.3,
        "2": 0.2
    },

    "item_probas":{
        "0":{
            "0": 0.5,
            "1": 0.2,
            "2": 0.3
        },
        "1":{
            "0": 0.1,
            "1": 0.6,
            "2": 0.3
        },
        "2": {
            "0": 0.2,
            "1": 0.1,
            "2": 0.7
        }
    }
    
    }



  probas2: |
    {
    "loc_probas": [ 0.5, 0.3, 0.2],
    "loc_name":   [ 0, 1, 2],
    
    "item_probas":{
          0: [ 0.5, 0.3, 0.2],
          1: [ 0.5, 0.3, 0.2],
          2: [ 0.5, 0.3, 0.2],
      }
    
    }
